# NumPy Basics: Arrays and Vectorized Computation
<br/>
NumPy, short for Numerical Python, is one of the most important foundational packages
for numerical computing in Python

## 4.1 The NumPy ndarray: A Multidimensional Array Object
NumPy最重要的一个特点就是其N维数组对象（即`ndarray` N-dimensional array），该对象是一个快速而灵活的大数据集容器。你可以利用这种数组对整块数据执行一些数学运算，其语法跟标量元素之间的运算一样。

In [2]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 0.14441242, -0.04810135,  1.37301052],
       [ 0.98422486,  0.07023101,  0.71134102]])

In [3]:
data * 10

array([[ 1.44412423, -0.48101352, 13.73010521],
       [ 9.84224861,  0.70231009,  7.11341016]])

In [4]:
data + data

array([[ 0.28882485, -0.0962027 ,  2.74602104],
       [ 1.96844972,  0.14046202,  1.42268203]])

ndarray是一个通用的同构数据多维容器，也就是说，其中的所有元素必须是相同类型的。每个数组都有一个shape（一个表示各维度大小的元组）和一个dtype（一个用于说明数组数据类型的对象）：

In [8]:
print(data.shape) #没有（）
print(data.dtype) #没有（）

(2, 3)
float64


### Creating ndarrays
创建数组最简单的办法就是使用array函数。它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# check dimensions of the arrays
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


#### Zeros & Ones

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

由于NumPy关注的是数值计算，因此，如果没有特别指定，数据类型基本都是float64。也可以用下面的表创建

| Function          | Description                                                                                                                                                                            |
|-------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| array             | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype; copies the input data by default           |
| asarray           | Convert input to ndarray, but do not copy if the input is already an ndarray                                                                                                           |
| arange            | Like the built-in range but returns an ndarray instead of a list                                                                                                                       |
| one, one_like     | Produce an array of all 1s with the given shape and dtype; ones_like takes another array and produces a ones array of the same shape and dtype                                         |
| zero, zero_like   | Like ones and ones_like but producing arrays of 0s instead                                                                                                                             |
| empty, empty_like | Create new arrays by allocating new memory, but do not populate with any values like ones and zeros                                                                                    |
| full, full_like   | Produce an array of the given shape and dtype with all values set to the indicated “fill value”, full_like takes another array and produces a filled array of the same shape and dtype |
| eye, identity     | Create a square N Å~ N identity matrix (1s on the diagonal and 0s elsewhere)                                                                                                           |